dist: trusty
sudo: false
language: generic
branches:
  only:
    - main
    - master
env:
  - SPELLCHECK=true
install:
  - conda env create --quiet --file build/environment.yml
  - conda list --name manubot
  - conda activate manubot
script:
  - sh build/build.sh
cache:
  directories:
    - ci/cache
deploy:
  provider: script
  script: bash ci/deploy.sh
  skip_cleanup: true
  on:
    # branch kept as master since travis deployment is legacy.
    branch: master
    condition: $TRAVIS_EVENT_TYPE = "push" && (-v MANUBOT_SSH_PRIVATE_KEY || "${!encrypted_*}" != "")
